import re
import time

from pptx import Presentation
from pptx.util import Inches, Pt

from backend.config import get_settings

TITLE_SLIDE_LAYOUT = 0
CONTENT_SLIDE_LAYOUT = 1


def _slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return f"{slug or 'presentation'}-{int(time.time())}"


def _reference_bullets(citations: list[dict]) -> list[str]:
    seen = set()
    bullets = []
    for c in citations:
        label = c.get("url") or c.get("source") or "Unknown source"
        if label in seen:
            continue
        seen.add(label)
        bullets.append(c.get("source", label) + (f" — {c['url']}" if c.get("url") else ""))
    return bullets


def _add_bullet_slide(prs: Presentation, title: str, bullets: list[str]) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[CONTENT_SLIDE_LAYOUT])
    slide.shapes.title.text = title
    body = slide.placeholders[1].text_frame
    body.clear()
    if not bullets:
        body.text = ""
        return
    body.text = bullets[0]
    for bullet in bullets[1:]:
        p = body.add_paragraph()
        p.text = bullet
        p.level = 0
    for paragraph in body.paragraphs:
        for run in paragraph.runs:
            run.font.size = Pt(18)


def generate_presentation(
    title: str,
    slide_titles: list[str],
    slide_content: dict[str, list[str]],
    citations: list[dict],
) -> str:
    settings = get_settings()
    presentations_dir = settings.resolved_path(settings.presentations_dir)
    path = presentations_dir / f"{_slugify(title)}.pptx"

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    title_slide = prs.slides.add_slide(prs.slide_layouts[TITLE_SLIDE_LAYOUT])
    title_slide.shapes.title.text = title
    if len(title_slide.placeholders) > 1:
        title_slide.placeholders[1].text = "Generated by AI Research Assistant"

    content_titles = [t for t in slide_titles if t.lower() not in {"title", "agenda", "references"}]
    if any(t.lower() == "agenda" for t in slide_titles):
        _add_bullet_slide(prs, "Agenda", content_titles)

    for slide_title in content_titles:
        _add_bullet_slide(prs, slide_title, slide_content.get(slide_title, []))

    if any(t.lower() == "references" for t in slide_titles):
        _add_bullet_slide(prs, "References", _reference_bullets(citations))

    prs.save(str(path))
    return str(path)
